# Generated by Django 4.2.7 on 2025-08-30 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del libro', max_length=200, verbose_name='Título')),
                ('autor', models.CharField(help_text='Nombre del autor', max_length=100, verbose_name='Autor')),
                ('isbn', models.CharField(help_text='Código ISBN del libro', max_length=13, unique=True, verbose_name='ISBN')),
                ('genero', models.CharField(choices=[('ficcion', 'Ficción'), ('no_ficcion', 'No Ficción'), ('ciencia', 'Ciencia'), ('historia', 'Historia'), ('biografia', 'Biografía'), ('tecnologia', 'Tecnología'), ('arte', 'Arte'), ('deportes', 'Deportes'), ('otros', 'Otros')], default='otros', max_length=20, verbose_name='Género')),
                ('editorial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Editorial')),
                ('año_publicacion', models.PositiveIntegerField(help_text='Año de publicación del libro', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2024)], verbose_name='Año de Publicación')),
                ('paginas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Páginas')),
                ('descripcion', models.TextField(blank=True, help_text='Breve descripción del contenido del libro', null=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('reservado', 'Reservado'), ('perdido', 'Perdido')], default='disponible', max_length=20, verbose_name='Estado')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['titulo', 'autor'],
                'indexes': [models.Index(fields=['titulo'], name='libros_libr_titulo_8b1204_idx'), models.Index(fields=['autor'], name='libros_libr_autor_285ad2_idx'), models.Index(fields=['isbn'], name='libros_libr_isbn_88473c_idx'), models.Index(fields=['estado'], name='libros_libr_estado_211437_idx')],
            },
        ),
    ]
