# Generated by Django 4.2.7 on 2025-09-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='libro',
            name='libros_libr_isbn_88473c_idx',
        ),
        migrations.RemoveIndex(
            model_name='libro',
            name='libros_libr_estado_211437_idx',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='editorial',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='paginas',
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['genero'], name='libros_libr_genero_56ce56_idx'),
        ),
    ]
